feat: support pre initialize number
travellocal/babel-plugin-declare-const-enum pull request #1
Opened 2022-12-04 12:55 UTC by RobinCodeX

2022-12-05 19:48 UTC, rikkit requested changes
Hey @RobinCodeX , thanks for the PR.

First off, I no longer need to use this package, so I don't have a good way to test regressions.

Can I just check I understand the use case correctly - if an enum member is not initialised with a numeric value, then this code will assign a value according to the same (?) rules that TypeScript assigns at compile-time. 

If that's correct, that makes sense and I'm happy to merge and release a new package if you can add an explainer comment to the new code. Cheers

2022-12-05 19:48 UTC, rikkit commented on src/typescriptUtils.ts
> +      }
I reckon this code needs an explainer comment on what its purpose is. Can you add one please?

2022-12-06 09:50 UTC, RobinCodeX commented on src/typescriptUtils.ts
> +      }
I've changed it and add debug option, I have a lot of enum, and the output of console.debug is too much.

2022-12-06 10:26 UTC, RobinCodeX commented on src/typescriptUtils.ts
> +      }
I have adjusted the test example and fixed some errors.

2022-12-06 10:31 UTC, rikkit commented on sample/numericSwitch/types.d.ts
> +  E = 11,
Just wondering if this is a case that's not handled, what is the expected value of `MyEnum.C` in the following enum?

```ts
enum MyEnum {
  A = 2,
  B = "STRING VAL",
  C,
}
```

2022-12-06 12:57 UTC, RobinCodeX commented on sample/numericSwitch/types.d.ts
> +  E = 11,
This throw an error from [typescriptUtils.ts#L58](https://github.com/RobinCodeX/babel-plugin-declare-const-enum/blob/next/src/typescriptUtils.ts#L58).
I have added a new test sample [errorEnum](https://github.com/RobinCodeX/babel-plugin-declare-const-enum/tree/next/sample/errorEnum)

2022-12-10 09:26 UTC, closed without merging